[package]
name = "polkadot-node-core-pvf-checker"
version = "0.9.29"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
thiserror = "1.0.31"
gum = { package = "tracing-gum", path = "../../gum" }

polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-overseer = { path = "../../overseer" }

sp-keystore = { git = "https://github.com/zeitgeistpm/substrate", branch = "moonbeam-polkadot-v0.9.29" }

[dev-dependencies]
sp-core = { git = "https://github.com/zeitgeistpm/substrate", branch = "moonbeam-polkadot-v0.9.29" }
sp-runtime = { git = "https://github.com/zeitgeistpm/substrate", branch = "moonbeam-polkadot-v0.9.29" }
sc-keystore = { git = "https://github.com/zeitgeistpm/substrate", branch = "moonbeam-polkadot-v0.9.29" }
sp-keyring = { git = "https://github.com/zeitgeistpm/substrate", branch = "moonbeam-polkadot-v0.9.29" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers"}
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
sp-application-crypto = { git = "https://github.com/zeitgeistpm/substrate", branch = "moonbeam-polkadot-v0.9.29" }
futures-timer = "3.0.2"
